// budget-wide
export const ADD_MONTH = 'ADD_MONTH';
export const SAVE = 'SAVE';
export const SET_VIEWED_MONTH = 'SET_VIEWED_MONTH';
// month specific
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const SET_CATEGORY_ROLLOVER = 'SET_CATEGORY_ROLLOVER';
export const SET_PROJECTED_INCOME = 'SET_PROJECTED_INCOME';
export const UPDATE_ACTUAL_INCOME = 'UPDATE_ACTUAL_INCOME';
export const UPDATE_CATEGORY_BUDGET = 'UPDATE_CATEGORY_BUDGET';
export const UPDATE_CATEGORY_SPENT = 'UPDATE_CATEGORY_SPENT';
